name = "BitBasis"
uuid = "50ba71b6-fa0f-514d-ae9a-0916efc90dcf"
version = "0.9.9"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
LinearAlgebra = "1"
StaticArrays = "1"
julia = "1.6"
